### ISSUE TITLE
Update to recent Angular Versions

### ISSUE THREAD

**Issue by ShahBinoy** [lbialy/play-ng2-webpack2#2]
Hi,

Can you please update the readme to validate if the angular-cli gotcha's are still valid? Is it possible to update the Angular version to recent version now

Thanks

**Comment by lbialy** [comment]
Please see: https://github.com/lbialy/play-ng2-webpack2/issues/3, cheers!

**Comment by lbialy** [comment]
Any ideas, comments and critique are welcome of course.

**Comment by lbialy** [comment]
Done!
